# ===========================================================
# MinIO 对象存储服务上游定义
# ===========================================================

# # MinIO S3 API
# upstream deer-flow-minio {
#     server minio:9000;
# }

# MinIO Console 控制台
upstream deer-flow-minio-console {
    server minio:9001;
}
